import { PrismaClient } from "@prisma/client";


// if you want to see the params of the query generated by prisma sql 
// basically to see the value of $1, $2 but don't do this everywhere cause sometime you are storing env vars in it but here it is just take and skip or 
// offset and limit
const prisma = new PrismaClient({
    log: [
        {
            emit: "event",
            level: "query"
        }
    ]
})

async function main(){
    const res = await prisma.post.findMany({
        take:2,
        skip:0
    })
    console.log(res)
}

main()
.then(async()=> {
    await prisma.$disconnect()
})
.catch(async(e)=> {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
})

prisma.$on("query", async(e)=> {
    console.log(`${e.query} ${e.params} ${e.duration} ${e.timestamp} `)
    
})